//! Runtime support for code generated by `sbe_gen`.
//!
//! Everything here used to be emitted into every generated message module, identically. None
//! of it varies with the schema, so it lives once, here, and the generated modules import it.

pub use sbe_gen_derive::sbe_gen;

use core::fmt;
use core::marker::PhantomData;

use zerocopy::byteorder::little_endian::{U16, U32, U64};
use zerocopy::{FromBytes, Immutable, IntoBytes, KnownLayout, Ref, Unaligned};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodeIntoError {
    BufferTooSmall { required: usize, available: usize },
    LengthOverflow { len: usize, max: usize },
    CountOverflow { count: usize, max: usize },
    InvalidState(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecodeFieldError {
    MissingField(&'static str),
    NullValue(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodeError {
    LengthOverflow { len: usize, max: usize },
    CountOverflow { count: usize, max: usize },
}

/// The SBE message header: the same four fields for every schema, so it lives here rather
/// than being emitted into a module per generated crate.
#[repr(C)]
#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]
pub struct MessageHeader {
    pub block_length: U16,
    pub template_id: U16,
    pub schema_id: U16,
    pub version: U16,
}

impl MessageHeader {
    pub const SIZE: usize = core::mem::size_of::<Self>();

    #[inline]
    pub fn parse_prefix(body: &[u8]) -> Option<(&Self, &[u8])> {
        parse_prefix(body)
    }

    // host integers in, bytes out: the derive writes this call and has no zerocopy in scope
    #[inline]
    pub fn new(block_length: u16, template_id: u16, schema_id: u16, version: u16) -> Self {
        Self {
            block_length: U16::new(block_length),
            template_id: U16::new(template_id),
            schema_id: U16::new(schema_id),
            version: U16::new(version),
        }
    }

    #[inline]
    pub fn to_bytes(&self) -> [u8; Self::SIZE] {
        let mut out = [0u8; Self::SIZE];
        out.copy_from_slice(self.as_bytes());
        out
    }
}

/// The block at the front of `body`, and whatever follows it.
#[inline]
pub fn parse_prefix<T: FromBytes + KnownLayout + Immutable>(body: &[u8]) -> Option<(&T, &[u8])> {
    Ref::<_, T>::from_prefix(body)
        .ok()
        .map(|(r, b)| (Ref::into_ref(r), b))
}

/// Reading a block off the front of a buffer. Every packed block qualifies, so this is blanket
/// and nothing has to write it. Kept because callers had it as an inherent method.
pub trait ParsePrefix: FromBytes + KnownLayout + Immutable + Sized {
    #[inline]
    fn parse_prefix(body: &[u8]) -> Option<(&Self, &[u8])> {
        parse_prefix(body)
    }
}

impl<T: FromBytes + KnownLayout + Immutable> ParsePrefix for T {}

/// A variable-length member: its declared length and the bytes it points at.
#[derive(Debug, Clone, Copy)]
pub struct VarData<'a> {
    pub len: usize,
    pub bytes: &'a [u8],
}

impl<'a> VarData<'a> {
    #[inline]
    pub fn as_str(&self) -> Option<&'a str> {
        core::str::from_utf8(self.bytes).ok()
    }
}

/// A var-data length prefix. The width is a type parameter rather than a runtime tag, so each
/// call site names its own and these helpers monomorphise.
pub trait Length: FromBytes + IntoBytes + Immutable + KnownLayout + Unaligned + Copy {
    const MAX: usize;
    fn to_usize(self) -> usize;
    fn from_usize(len: usize) -> Self;
}

// one row per width; `u8` is plain because a single byte has no byte order
macro_rules! lengths {
    ($($ty:ty => $host:ty, |$v:ident| $read:expr, |$n:ident| $build:expr;)+) => {
        $(impl Length for $ty {
            const MAX: usize = <$host>::MAX as usize;
            #[inline]
            fn to_usize(self) -> usize {
                let $v = self;
                $read as usize
            }
            #[inline]
            fn from_usize(len: usize) -> Self {
                let $n = len as $host;
                $build
            }
        })+
    };
}

lengths! {
    u8  => u8,  |v| v,       |n| n;
    U16 => u16, |v| v.get(), |n| U16::new(n);
    U32 => u32, |v| v.get(), |n| U32::new(n);
    U64 => u64, |v| v.get(), |n| U64::new(n);
}

#[inline]
pub fn parse_var_data<'a, T: Length>(buf: &'a [u8]) -> Option<(VarData<'a>, &'a [u8])> {
    let (prefix, rest) = Ref::<_, T>::from_prefix(buf).ok()?;
    let len = T::to_usize(*prefix);
    if rest.len() < len {
        return None;
    }
    let (bytes, tail) = rest.split_at(len);
    Some((VarData { len, bytes }, tail))
}

/// The growing buffer a builder appends into.
///
/// A trait rather than `Vec<u8>` because the allocator crate is optional: a type parameter is
/// the only spelling of "a vector, possibly someone else's" that compiles whether or not it is
/// switched on, and generated code is written once for both.
pub trait Buf {
    /// what `new_in` takes. std's `Vec` has no allocator to name, so it takes nothing.
    type Alloc;
    fn new_in(alloc: Self::Alloc) -> Self;
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
    fn resize_zeroed(&mut self, len: usize);
    fn extend_from_slice(&mut self, bytes: &[u8]);
    fn as_slice(&self) -> &[u8];
    fn as_mut_slice(&mut self) -> &mut [u8];
}

impl Buf for Vec<u8> {
    type Alloc = ();
    fn new_in((): ()) -> Self {
        Self::new()
    }
    fn len(&self) -> usize {
        self.len()
    }
    fn resize_zeroed(&mut self, len: usize) {
        self.resize(len, 0);
    }
    fn extend_from_slice(&mut self, bytes: &[u8]) {
        self.extend_from_slice(bytes);
    }
    fn as_slice(&self) -> &[u8] {
        self
    }
    fn as_mut_slice(&mut self) -> &mut [u8] {
        self
    }
}

#[cfg(feature = "allocator-api2")]
impl<A: allocator_api2::alloc::Allocator> Buf for allocator_api2::vec::Vec<u8, A> {
    type Alloc = A;
    fn new_in(alloc: A) -> Self {
        Self::new_in(alloc)
    }
    fn len(&self) -> usize {
        self.len()
    }
    fn resize_zeroed(&mut self, len: usize) {
        self.resize(len, 0);
    }
    fn extend_from_slice(&mut self, bytes: &[u8]) {
        self.extend_from_slice(bytes);
    }
    fn as_slice(&self) -> &[u8] {
        self
    }
    fn as_mut_slice(&mut self) -> &mut [u8] {
        self
    }
}

#[inline]
pub fn write_var_data<T: Length, B: Buf>(buf: &mut B, bytes: &[u8]) -> Result<(), EncodeError> {
    let len = bytes.len();
    if len > T::MAX {
        return Err(EncodeError::LengthOverflow { len, max: T::MAX });
    }
    buf.extend_from_slice(T::from_usize(len).as_bytes());
    buf.extend_from_slice(bytes);
    Ok(())
}

#[inline]
pub fn write_var_data_into<T: Length>(
    dst: &mut [u8],
    offset: usize,
    bytes: &[u8],
) -> Result<usize, EncodeIntoError> {
    let len = bytes.len();
    if len > T::MAX {
        return Err(EncodeIntoError::LengthOverflow { len, max: T::MAX });
    }
    let prefix = core::mem::size_of::<T>();
    let data_start = offset + prefix;
    let data_end = data_start + len;
    if data_end > dst.len() {
        return Err(EncodeIntoError::BufferTooSmall {
            required: data_end,
            available: dst.len(),
        });
    }
    dst[offset..data_start].copy_from_slice(T::from_usize(len).as_bytes());
    dst[data_start..data_end].copy_from_slice(bytes);
    Ok(prefix + len)
}

#[inline]
pub fn ensure_len<B: Buf>(buf: &mut B, len: usize) {
    if buf.len() < len {
        buf.resize_zeroed(len);
    }
}

#[inline]
pub fn write_bytes_at<T: IntoBytes + Immutable, B: Buf>(buf: &mut B, offset: usize, value: &T) {
    let bytes = value.as_bytes();
    ensure_len(buf, offset + bytes.len());
    buf.as_mut_slice()[offset..offset + bytes.len()].copy_from_slice(bytes);
}

#[inline]
pub fn write_bytes_into<T: IntoBytes + Immutable>(
    dst: &mut [u8],
    offset: usize,
    value: &T,
) -> Result<(), EncodeIntoError> {
    let bytes = value.as_bytes();
    let end = offset + bytes.len();
    if end > dst.len() {
        return Err(EncodeIntoError::BufferTooSmall {
            required: end,
            available: dst.len(),
        });
    }
    dst[offset..end].copy_from_slice(bytes);
    Ok(())
}

#[inline]
pub fn write_bytes_into_in_bounds<T: IntoBytes + Immutable>(
    dst: &mut [u8],
    offset: usize,
    value: &T,
) {
    let bytes = value.as_bytes();
    let end = offset + bytes.len();
    debug_assert!(end <= dst.len(), "fixed field write in bounds");
    dst[offset..end].copy_from_slice(bytes);
}

/// SBE pads fixed-length character fields on the right, with either spaces or NULs depending
/// on the venue, so both are trimmed.
#[inline]
pub fn trim_ascii_space_and_nul_right(mut bytes: &[u8]) -> &[u8] {
    while let Some((&last, rest)) = bytes.split_last() {
        if last == b' ' || last == 0 {
            bytes = rest;
        } else {
            break;
        }
    }
    bytes
}

/// A group's dimension header. Which two members carry the count and the block length, and how
/// wide the schema made them, is only knowable from the XML, so the composite gets this written
/// for it and everything above here is generic.
pub trait Dimension: Sized {
    const SIZE: usize;
    /// the largest count the schema's chosen integer can express
    const MAX_COUNT: usize;

    // not `parse_prefix`: every composite already has an inherent one of those, and an inherent
    // method wins resolution, so a trait method sharing the name would call itself
    fn parse_header(body: &[u8]) -> Option<(&Self, &[u8])>;
    fn count(&self) -> usize;
    fn block_length(&self) -> usize;

    fn write_block<B: Buf>(buf: &mut B, at: usize, block_length: usize);
    fn write_count<B: Buf>(buf: &mut B, at: usize, count: usize);
    fn write_block_into(
        dst: &mut [u8],
        at: usize,
        block_length: usize,
    ) -> Result<(), EncodeIntoError>;
    fn write_count_into(dst: &mut [u8], at: usize, count: usize) -> Result<(), EncodeIntoError>;
}

/// Writing a message into memory the caller already owns.
///
/// The three items below are all a message declares; the two that callers actually use are the
/// same for every message, so they are written once here rather than into each module.
pub trait MessageEncode {
    type Encoder<'a>;
    fn encoder(dst: &mut [u8]) -> Result<Self::Encoder<'_>, EncodeIntoError>;
    fn finish(encoder: Self::Encoder<'_>) -> usize;

    /// the body — fixed block then variable data — and how many bytes it took
    fn encode_body_into<F>(dst: &mut [u8], f: F) -> Result<usize, EncodeIntoError>
    where
        F: FnOnce(&mut Self::Encoder<'_>) -> Result<(), EncodeIntoError>,
    {
        let mut encoder = Self::encoder(dst)?;
        f(&mut encoder)?;
        Ok(Self::finish(encoder))
    }

    /// the same, behind a message header. `dst` has to fit `MessageHeader::SIZE + body`.
    fn encode_with_header_into<F>(
        dst: &mut [u8],
        header: MessageHeader,
        f: F,
    ) -> Result<usize, EncodeIntoError>
    where
        F: FnOnce(&mut Self::Encoder<'_>) -> Result<(), EncodeIntoError>,
    {
        if dst.len() < MessageHeader::SIZE {
            return Err(EncodeIntoError::BufferTooSmall {
                required: MessageHeader::SIZE,
                available: dst.len(),
            });
        }
        let body = {
            let (_, body_dst) = dst.split_at_mut(MessageHeader::SIZE);
            let mut encoder = Self::encoder(body_dst)?;
            f(&mut encoder)?;
            Self::finish(encoder)
        };
        let total = MessageHeader::SIZE + body;
        if dst.len() < total {
            return Err(EncodeIntoError::BufferTooSmall {
                required: total,
                available: dst.len(),
            });
        }
        write_bytes_into(dst, 0, &header)?;
        Ok(total)
    }
}

/// The entry type names its own builder and encoder, so the group machinery can make one
/// without knowing what setters the schema gave it. It is a GAT because the builder borrows
/// the buffer for each entry, not for the group.
pub trait GroupEntryBuilder<B: Buf = Vec<u8>> {
    type Builder<'b>
    where
        B: 'b;
    fn builder(buf: &mut B, start: usize) -> Self::Builder<'_>;
}

pub trait GroupEntryEncoder {
    type Encoder<'b>;
    /// bytes an entry's fixed block occupies
    const FIXED_LEN: usize;
    fn encoder(buf: &mut [u8], cursor: usize) -> Result<Self::Encoder<'_>, EncodeIntoError>;
    fn finish(encoder: Self::Encoder<'_>) -> usize;
}

/// Appends a group to a growing `Vec`. Counts entries as they are written and stamps the
/// number into the header on `finish`, which is the only point the total is known.
pub struct GroupBuilder<'a, D, E, const BLOCK_LENGTH: usize, B = Vec<u8>> {
    buf: &'a mut B,
    header_start: usize,
    count: usize,
    overflow: usize,
    entry: PhantomData<(D, E)>,
}

impl<'a, D: Dimension, E: GroupEntryBuilder<BUF>, const B: usize, BUF: Buf>
    GroupBuilder<'a, D, E, B, BUF>
{
    pub const BLOCK_LENGTH: u16 = B as u16;
    pub const HEADER_SIZE: usize = D::SIZE;
    pub const MAX_COUNT: usize = D::MAX_COUNT;

    pub fn new(buf: &'a mut BUF) -> Self {
        let header_start = buf.len();
        buf.resize_zeroed(header_start + D::SIZE);
        D::write_block(buf, header_start, B);
        D::write_count(buf, header_start, 0);
        Self {
            buf,
            header_start,
            count: 0,
            overflow: 0,
            entry: PhantomData,
        }
    }

    // an over-count is held back rather than returned here, because the caller chains these
    pub fn entry<F: FnOnce(&mut E::Builder<'_>)>(&mut self, f: F) -> &mut Self {
        if self.count >= D::MAX_COUNT {
            self.overflow = self.overflow.saturating_add(1);
            return self;
        }
        let start = self.buf.len();
        self.buf.resize_zeroed(start + B);
        f(&mut E::builder(self.buf, start));
        self.count += 1;
        self
    }

    pub fn finish(self) -> Result<(), EncodeError> {
        let total = self.count.saturating_add(self.overflow);
        if total > D::MAX_COUNT {
            return Err(EncodeError::CountOverflow {
                count: total,
                max: D::MAX_COUNT,
            });
        }
        D::write_count(self.buf, self.header_start, self.count);
        Ok(())
    }
}

/// The same, into a buffer that is already the right size.
pub struct GroupEncoder<'a, D, E, const BLOCK_LENGTH: usize> {
    buf: &'a mut [u8],
    cursor: usize,
    header_start: usize,
    count: usize,
    entry: PhantomData<(D, E)>,
}

impl<'a, D: Dimension, E: GroupEntryEncoder, const B: usize> GroupEncoder<'a, D, E, B> {
    pub const BLOCK_LENGTH: u16 = B as u16;
    pub const HEADER_SIZE: usize = D::SIZE;
    pub const MAX_COUNT: usize = D::MAX_COUNT;
    pub const ENTRY_FIXED_LEN: usize = E::FIXED_LEN;

    pub fn new(buf: &'a mut [u8], cursor: usize) -> Result<Self, EncodeIntoError> {
        let header_end = cursor + D::SIZE;
        if header_end > buf.len() {
            return Err(EncodeIntoError::BufferTooSmall {
                required: header_end,
                available: buf.len(),
            });
        }
        buf[cursor..header_end].fill(0);
        D::write_block_into(buf, cursor, B)?;
        D::write_count_into(buf, cursor, 0)?;
        Ok(Self {
            buf,
            cursor: header_end,
            header_start: cursor,
            count: 0,
            entry: PhantomData,
        })
    }

    pub fn entry<F>(&mut self, f: F) -> Result<&mut Self, EncodeIntoError>
    where
        F: FnOnce(&mut E::Encoder<'_>) -> Result<(), EncodeIntoError>,
    {
        if self.count >= D::MAX_COUNT {
            return Err(EncodeIntoError::CountOverflow {
                count: self.count.saturating_add(1),
                max: D::MAX_COUNT,
            });
        }
        let mut entry = E::encoder(self.buf, self.cursor)?;
        f(&mut entry)?;
        self.cursor = E::finish(entry);
        self.count += 1;
        Ok(self)
    }

    pub fn finish(self) -> Result<usize, EncodeIntoError> {
        D::write_count_into(self.buf, self.header_start, self.count)?;
        Ok(self.cursor)
    }
}

/// A repeating group: its dimension header, and the bytes its entries were written into.
///
/// `SINCE_VERSION` and `BLOCK_LENGTH` are const parameters so that everything a schema group
/// varies by lands in the type arguments, and the generated module writes a `type` alias
/// instead of another struct with another copy of these four methods.
pub struct Group<'a, D, V, const SINCE_VERSION: u32, const BLOCK_LENGTH: usize> {
    pub header: &'a D,
    payload: &'a [u8],
    block_length: usize,
    entry: PhantomData<V>,
}

impl<'a, D: Dimension, V, const S: u32, const B: usize> Group<'a, D, V, S, B> {
    pub const SINCE_VERSION: u32 = S;
    pub const BLOCK_LENGTH: usize = B;

    pub fn parse(buf: &'a [u8]) -> Option<Self> {
        let (header, payload) = D::parse_header(buf)?;
        // a zero in the header means the writer left it out, so the schema's own number stands
        let block_length = match header.block_length() {
            0 => B,
            n => n,
        };
        Some(Self {
            header,
            payload,
            block_length,
            entry: PhantomData,
        })
    }

    pub fn count(&self) -> usize {
        self.header.count()
    }

    pub fn iter(&self) -> GroupIter<'a, V> {
        GroupIter::new(self.payload, self.count(), self.block_length)
    }
}

impl<'a, D: Dimension, V: GroupEntry<'a>, const S: u32, const B: usize> Group<'a, D, V, S, B> {
    /// The bytes after this group's entries.
    ///
    /// Walks them rather than multiplying by a stride, because an entry carrying its own groups
    /// or var-data is as long as its contents and there is no stride to multiply by.
    pub fn skip(&self) -> Option<&'a [u8]> {
        let mut entries = self.iter();
        for _ in 0..self.count() {
            entries.next()?;
        }
        Some(entries.remainder())
    }
}

// hand-written because deriving would put `V: Clone`/`V: Copy` on the impl, and an entry view
// carrying nested groups is Clone but not Copy — the group itself is three words either way
impl<D, V, const S: u32, const B: usize> Clone for Group<'_, D, V, S, B> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<D, V, const S: u32, const B: usize> Copy for Group<'_, D, V, S, B> {}

impl<D: fmt::Debug, V, const S: u32, const B: usize> fmt::Debug for Group<'_, D, V, S, B> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Group")
            .field("header", &self.header)
            .field("block_length", &self.block_length)
            .finish()
    }
}

/// One entry's fixed block.
///
/// `parsed` is `None` when the writer's block is shorter than the struct this build knows — a
/// message written against an older version of the schema — and then the accessors read `raw`
/// field by field instead, so the entry still decodes as far as it goes.
#[derive(Debug, Clone, Copy)]
pub struct EntryBody<'a, E> {
    pub parsed: Option<&'a E>,
    pub raw: &'a [u8],
}

impl<'a, E: FromBytes + KnownLayout + Immutable> EntryBody<'a, E> {
    pub fn parse(entry: &'a [u8], block_length: usize) -> Option<Self> {
        if entry.len() < block_length {
            return None;
        }
        let needed = core::mem::size_of::<E>();
        let (parsed, raw) = if block_length >= needed {
            let raw = &entry[..needed];
            let (body, _) = Ref::<_, E>::from_prefix(raw).ok()?;
            (Some(Ref::into_ref(body)), raw)
        } else {
            (None, &entry[..block_length])
        };
        Some(Self { parsed, raw })
    }
}

impl<E> core::ops::Deref for EntryBody<'_, E> {
    type Target = E;

    fn deref(&self) -> &E {
        self.parsed
            .expect("body shorter than the layout this build knows; use the accessors")
    }
}

/// One entry of a repeating group.
///
/// An entry is `block_length` bytes of fixed fields, then whatever else it carries: each nested
/// group with its own dimension header and entries, then each var-data with its length prefix.
/// How much that comes to depends on the entry's own contents, which is why this hands back the
/// bytes it stopped at rather than the iterator computing a stride.
pub trait GroupEntry<'a>: Sized {
    fn parse_entry(cursor: &'a [u8], block_length: usize) -> Option<(Self, &'a [u8])>;
}

/// Walks a group's entries. The width comes off the group's dimension header rather than
/// `size_of`, so a message written against a newer schema — one that appended fields to the
/// entry — still decodes: the extra bytes are skipped instead of shifting every later entry.
pub struct GroupIter<'a, V> {
    remaining: &'a [u8],
    entries_left: usize,
    block_length: usize,
    entry: PhantomData<V>,
}

impl<'a, V> GroupIter<'a, V> {
    #[inline]
    pub fn new(payload: &'a [u8], entries_left: usize, block_length: usize) -> Self {
        Self {
            remaining: payload,
            entries_left,
            block_length,
            entry: PhantomData,
        }
    }

    /// what is left after the entries: the next group's header, or the var-data
    #[inline]
    pub fn remainder(&self) -> &'a [u8] {
        self.remaining
    }
}

impl<'a, V: GroupEntry<'a>> Iterator for GroupIter<'a, V> {
    type Item = V;

    fn next(&mut self) -> Option<V> {
        if self.entries_left == 0 {
            return None;
        }
        let (entry, rest) = V::parse_entry(self.remaining, self.block_length)?;
        self.remaining = rest;
        self.entries_left -= 1;
        Some(entry)
    }
}

/// `#[serde(with = ..)]` targets for the wire types.
///
/// A block's fields are zerocopy wrappers and byte arrays. Neither is `Serialize`, and both are
/// foreign, so neither can be given one here.
#[cfg(feature = "serde")]
pub mod serde_wire {
    use super::*;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use zerocopy::byteorder::little_endian::{I16, I32, I64};

    /// the host integer a wire type carries
    pub trait Wire: Sized {
        type Host: Serialize + for<'de> Deserialize<'de>;
        fn to_host(&self) -> Self::Host;
        fn from_host(host: Self::Host) -> Self;
    }

    macro_rules! wire {
        ($($ty:ty => $host:ty, |$v:ident| $read:expr, |$h:ident| $build:expr;)+) => {
            $(impl Wire for $ty {
                type Host = $host;
                #[inline]
                fn to_host(&self) -> $host {
                    let $v = self;
                    $read
                }
                #[inline]
                fn from_host($h: $host) -> Self {
                    $build
                }
            })+
        };
    }

    wire! {
        u8  => u8,  |v| *v,      |h| h;
        i8  => i8,  |v| *v,      |h| h;
        U16 => u16, |v| v.get(), |h| U16::new(h);
        U32 => u32, |v| v.get(), |h| U32::new(h);
        U64 => u64, |v| v.get(), |h| U64::new(h);
        I16 => i16, |v| v.get(), |h| I16::new(h);
        I32 => i32, |v| v.get(), |h| I32::new(h);
        I64 => i64, |v| v.get(), |h| I64::new(h);
    }

    pub fn serialize<W: Wire, S: Serializer>(value: &W, s: S) -> Result<S::Ok, S::Error> {
        value.to_host().serialize(s)
    }

    pub fn deserialize<'de, W: Wire, D: Deserializer<'de>>(d: D) -> Result<W, D::Error> {
        W::Host::deserialize(d).map(W::from_host)
    }
}

/// The same for a fixed-length character field, which SBE pads on the right.
#[cfg(feature = "serde")]
pub mod serde_ascii {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<const N: usize, S: Serializer>(
        value: &[u8; N],
        s: S,
    ) -> Result<S::Ok, S::Error> {
        match core::str::from_utf8(super::trim_ascii_space_and_nul_right(value)) {
            Ok(text) => s.serialize_str(text),
            Err(_) => s.serialize_bytes(value),
        }
    }

    pub fn deserialize<'de, const N: usize, D: Deserializer<'de>>(
        d: D,
    ) -> Result<[u8; N], D::Error> {
        let text = String::deserialize(d)?;
        let mut out = [0u8; N];
        let bytes = text.as_bytes();
        if bytes.len() > N {
            return Err(serde::de::Error::custom("too long for the field"));
        }
        out[..bytes.len()].copy_from_slice(bytes);
        Ok(out)
    }
}

/// Padding is not written to JSON, so deserialising has to put something back.
#[cfg(feature = "serde")]
pub fn zeroed<T: zerocopy::FromZeros>() -> T {
    T::new_zeroed()
}
