use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use sbe_gen::{generate_to, GeneratorOptions};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let schemas_dir = manifest_dir.join("schemas");
    let generated_root = manifest_dir.join("src/generated");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", schemas_dir.display());

    fs::create_dir_all(&generated_root)?;

    let mut schema_dirs: Vec<PathBuf> = fs::read_dir(&schemas_dir)?
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .map(|entry| entry.path())
        .collect();
    schema_dirs.sort();

    if schema_dirs.is_empty() {
        return Err(format!(
            "no schema directories found under {}",
            schemas_dir.display()
        )
        .into());
    }

    let mut modules = Vec::new();
    for schema_dir in schema_dirs {
        let schema_name = schema_dir
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| format!("invalid schema directory name {}", schema_dir.display()))?
            .to_string();

        let schema_xml = pick_schema_xml(&schema_dir)?;
        println!("cargo:rerun-if-changed={}", schema_xml.display());
        let schema_contents = fs::read_to_string(&schema_xml)
            .map_err(|e| format!("failed to read {}: {}", schema_xml.display(), e))?;

        let output_dir = generated_root.join(&schema_name);
        fs::create_dir_all(&output_dir)?;
        run_generator(&schema_contents, &schema_xml, &output_dir)?;
        patch_try_into_casts(&output_dir)?;
        patch_types_file(&output_dir)?;
        patch_allow_attrs(&output_dir)?;
        format_generated(&output_dir)?;

        modules.push(schema_name);
    }

    write_generated_mod(&generated_root, &modules)?;
    Ok(())
}

fn pick_schema_xml(dir: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let preferred = dir.join("templates_FixBinary.xml");
    if preferred.is_file() {
        return Ok(preferred);
    }

    let mut xml_files: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().map(|ext| ext == "xml").unwrap_or(false))
        .collect();
    xml_files.sort();

    match xml_files.len() {
        0 => Err(format!("no XML schema file found in {}", dir.display()).into()),
        1 => Ok(xml_files.remove(0)),
        _ => Err(format!(
            "multiple XML files found in {}, pick one via templates_FixBinary.xml",
            dir.display()
        )
        .into()),
    }
}

fn run_generator(schema: &str, schema_path: &Path, output: &Path) -> Result<(), Box<dyn Error>> {
    let opts = GeneratorOptions::default();
    generate_to(schema, output, &opts).map_err(|e| {
        format!(
            "sbe_gen failed for schema {} -> {}: {}",
            schema_path.display(),
            output.display(),
            e
        )
        .into()
    })
}

fn write_generated_mod(root: &Path, modules: &[String]) -> Result<(), Box<dyn Error>> {
    let mut buf = String::from("// @generated by build.rs; do not edit\n");
    for module in modules {
        buf.push_str(&format!("pub mod {};\n", module));
    }
    fs::write(root.join("mod.rs"), buf)?;
    Ok(())
}

fn patch_try_into_casts(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let pattern = "let count = (self.count.try_into().unwrap()) as u8;";
    let replacement = "let count: u8 = self.count.try_into().expect(\"count fits in u8\");";
    let mut stack = vec![output_dir.to_path_buf()];

    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            let file_type = entry.file_type()?;
            if file_type.is_dir() {
                stack.push(path);
            } else if file_type.is_file()
                && path.extension().map(|ext| ext == "rs").unwrap_or(false)
            {
                let contents = fs::read_to_string(&path)?;
                if contents.contains(pattern) {
                    let updated = contents.replace(pattern, replacement);
                    fs::write(&path, updated)?;
                }
            }
        }
    }

    Ok(())
}

fn patch_types_file(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let path = output_dir.join("types.rs");
    let mut contents = fs::read_to_string(&path)?;

    let literal_fixes = [
        ("<u8>::new(B)", "<u8>::new(b'B')"),
        ("<u8>::new(C)", "<u8>::new(b'C')"),
        ("<u8>::new(E)", "<u8>::new(b'E')"),
        ("<u8>::new(F)", "<u8>::new(b'F')"),
        ("<u8>::new(J)", "<u8>::new(b'J')"),
        ("<u8>::new(N)", "<u8>::new(b'N')"),
        ("<u8>::new(O)", "<u8>::new(b'O')"),
        ("<u8>::new(W)", "<u8>::new(b'W')"),
        ("<u8>::new(e)", "<u8>::new(b'e')"),
        ("<u8>::new(g)", "<u8>::new(b'g')"),
        ("<u8>::new(w)", "<u8>::new(b'w')"),
        ("<u8>::new(x)", "<u8>::new(b'x')"),
        ("<u8>::new(A)", "<u8>::new(b'A')"),
        ("<u8>::new(D)", "<u8>::new(b'D')"),
        ("<u8>::new(M)", "<u8>::new(b'M')"),
    ];
    for (from, to) in literal_fixes {
        contents = contents.replace(from, to);
    }
    contents = contents.replace("<u8>::new(", "(");

    let type_aliases = [
        (
            "pub const MDUpdateTypeNew: i8 = 0 as i8;",
            "pub type MDUpdateTypeNew = MDUpdateAction;",
        ),
        (
            "pub const MDUpdateActionNew: i8 = 0 as i8;",
            "pub type MDUpdateActionNew = MDUpdateAction;",
        ),
        (
            "pub const MDEntryTypeChannelReset: u8 = J as u8;",
            "pub type MDEntryTypeChannelReset = MDEntryType;",
        ),
        (
            "pub const MDEntryTypeLimits: u8 = g as u8;",
            "pub type MDEntryTypeLimits = MDEntryType;",
        ),
        (
            "pub const MDEntryTypeTrade: u8 = 2 as u8;",
            "pub type MDEntryTypeTrade = MDEntryType;",
        ),
        (
            "pub const MDEntryTypeVol: u8 = e as u8;",
            "pub type MDEntryTypeVol = MDEntryType;",
        ),
        (
            "pub const InstAttribType: i8 = 24 as i8;",
            "pub type InstAttribType = i8;",
        ),
    ];
    for (from, to) in type_aliases {
        contents = contents.replace(from, to);
    }

    // Ensure wide bitflags fit in u8 without const-eval overflow by casting from u32.
    for n in 0..=27 {
        let from = format!("Self((1 << {}))", n);
        let to = format!("Self(((1u32 << {}) as u8))", n);
        contents = contents.replace(&from, &to);
    }

    fs::write(&path, contents)?;
    Ok(())
}

fn patch_allow_attrs(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let allow_line = "#![allow(clippy::all, non_upper_case_globals, unused_parens, unused_imports, unused_mut)]\n";
    let mut stack = vec![output_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            let file_type = entry.file_type()?;
            if file_type.is_dir() {
                stack.push(path);
            } else if file_type.is_file()
                && path.extension().map(|ext| ext == "rs").unwrap_or(false)
            {
                let content = fs::read_to_string(&path)?;
                let desired = allow_line.trim_end();
                let new_content = if content.starts_with("#![allow(") {
                    let remainder = content.split_once('\n').map(|(_, rest)| rest).unwrap_or("");
                    format!("{}\n{}", desired, remainder)
                } else {
                    format!("{}{}", allow_line, content)
                };

                if new_content != content {
                    fs::write(&path, new_content)?;
                }
            }
        }
    }
    Ok(())
}

fn format_generated(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let mut files = Vec::new();
    let mut stack = vec![output_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            if entry.file_type()?.is_dir() {
                stack.push(path);
            } else if path.extension().map(|ext| ext == "rs").unwrap_or(false) {
                files.push(path);
            }
        }
    }

    files.sort();
    if files.is_empty() {
        return Ok(());
    }

    let status = Command::new("rustfmt").args(&files).status()?;
    if status.success() {
        Ok(())
    } else {
        Err("rustfmt failed on generated sources".into())
    }
}
