use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use sbe_gen::{DeriveSerialize, GeneratorOptions, generate_to_with};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let schemas_dir = manifest_dir.join("schemas");
    let generated_root = manifest_dir.join("src/generated");
    let sbe_gen_root = manifest_dir.join("..").join("..");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", schemas_dir.display());
    let sbe_gen_toml = sbe_gen_root.join("Cargo.toml");
    if sbe_gen_toml.is_file() {
        println!("cargo:rerun-if-changed={}", sbe_gen_toml.display());
        println!(
            "cargo:rerun-if-changed={}",
            sbe_gen_root.join("src").display()
        );
    }

    fs::create_dir_all(&generated_root)?;

    // Collect and sort all subdirectories under schemas/.
    let mut schema_dirs: Vec<PathBuf> = fs::read_dir(&schemas_dir)?
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .map(|entry| entry.path())
        .collect();
    schema_dirs.sort();

    // Fail if there are no subdirectories.
    if schema_dirs.is_empty() {
        return Err(format!(
            "no schema directories found under {}",
            schemas_dir.display()
        )
        .into());
    }

    let generator_opts = generator_options();
    let mut modules = Vec::new();

    // schema loop: for each schema directory
    for schema_dir in schema_dirs {
        // derive schema name from schema directory name
        let schema_name = schema_dir
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| format!("invalid schema directory name {}", schema_dir.display()))?
            .to_string();

        let schema_xml = pick_schema_xml(&schema_dir)?;
        println!("cargo:rerun-if-changed={}", schema_xml.display());
        let schema_contents = fs::read_to_string(&schema_xml)
            .map_err(|e| format!("failed to read {}: {}", schema_xml.display(), e))?;

        // Create the output directory: src/generated/<schema_name>.
        let output_dir = generated_root.join(&schema_name);
        fs::create_dir_all(&output_dir)?;

        run_generator(&schema_contents, &schema_xml, &output_dir, &generator_opts)?;
        // run rustfmt
        format_generated(&output_dir)?;

        modules.push(schema_name);
    }

    write_generated_mod(&generated_root, &modules)?;
    Ok(())
}

/// select the schema file:
///  - Prefer templates_FixBinary.xml if present.
///  - Otherwise, require exactly one .xml; error if zero or multiple.
fn pick_schema_xml(dir: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let preferred = dir.join("templates_FixBinary.xml");
    if preferred.is_file() {
        return Ok(preferred);
    }

    let mut xml_files: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().map(|ext| ext == "xml").unwrap_or(false))
        .collect();
    xml_files.sort();

    match xml_files.len() {
        0 => Err(format!("no XML schema file found in {}", dir.display()).into()),
        1 => Ok(xml_files.remove(0)),
        _ => Err(format!(
            "multiple XML files found in {}, pick one via templates_FixBinary.xml",
            dir.display()
        )
        .into()),
    }
}

fn run_generator(
    schema: &str,
    schema_path: &Path,
    output: &Path,
    opts: &GeneratorOptions,
) -> Result<(), Box<dyn Error>> {
    let serde =
        DeriveSerialize::default().map_semantic("UTCTimestamp", "crate::json_types::utc_timestamp");
    generate_to_with(schema, output, opts, &[&serde]).map_err(|e| {
        format!(
            "sbe_gen failed for schema {} -> {}: {}",
            schema_path.display(),
            output.display(),
            e
        )
        .into()
    })
}

fn generator_options() -> GeneratorOptions {
    GeneratorOptions {
        allow_attr: Some(
            "#![allow(clippy::all, non_upper_case_globals, unused_parens, unused_imports, unused_mut)]"
                .to_string(),
        ),
        // laid out identically to what the schema declares, so it is read off the wire rather
        // than converted
        type_map: [("PRICE9", "crate::json_types::Price9")]
            .into_iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect(),
        ..Default::default()
    }
}

fn write_generated_mod(root: &Path, modules: &[String]) -> Result<(), Box<dyn Error>> {
    let mut buf = String::from("// @generated by build.rs; do not edit\n");
    for module in modules {
        buf.push_str(&format!("pub mod {};\n", module));
    }
    fs::write(root.join("mod.rs"), buf)?;
    Ok(())
}

/// Run rustfmt across all generated .rs files in the output directory.
fn format_generated(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let mut files = Vec::new();
    let mut stack = vec![output_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            if entry.file_type()?.is_dir() {
                stack.push(path);
            } else if path.extension().map(|ext| ext == "rs").unwrap_or(false) {
                files.push(path);
            }
        }
    }

    files.sort();
    if files.is_empty() {
        return Ok(());
    }

    let edition = env::var("CARGO_PKG_EDITION").unwrap_or_else(|_| "2024".to_string());
    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg(edition)
        .args(&files)
        .status()?;
    if status.success() {
        Ok(())
    } else {
        Err("rustfmt failed on generated sources".into())
    }
}
