//! Code generation for parsed SBE schemas.
//!
//! The generator produces one Rust module per message along with a
//! `types.rs` module which contains definitions for user defined
//! enums, sets and composites.  A `mod.rs` file is also emitted to
//! re‑export the generated types for ergonomic use.

use crate::parser::{
    CompositeField, Field, Group, GroupMember, Message, MessageMember, Schema, TypeDef,
    VarDataField,
};
use crate::GeneratorOptions;
use heck::ToSnakeCase;

fn message_fields(msg: &Message) -> Vec<&Field> {
    msg.members
        .iter()
        .filter_map(|m| {
            if let MessageMember::Field(f) = m {
                Some(f)
            } else {
                None
            }
        })
        .collect()
}

fn message_groups(msg: &Message) -> Vec<&Group> {
    msg.members
        .iter()
        .filter_map(|m| {
            if let MessageMember::Group(g) = m {
                Some(g)
            } else {
                None
            }
        })
        .collect()
}

fn message_data(msg: &Message) -> Vec<&VarDataField> {
    msg.members
        .iter()
        .filter_map(|m| {
            if let MessageMember::Data(d) = m {
                Some(d)
            } else {
                None
            }
        })
        .collect()
}

fn group_fields(g: &Group) -> Vec<&Field> {
    g.members
        .iter()
        .filter_map(|m| {
            if let GroupMember::Field(f) = m {
                Some(f)
            } else {
                None
            }
        })
        .collect()
}

fn group_data(g: &Group) -> Vec<&VarDataField> {
    g.members
        .iter()
        .filter_map(|m| {
            if let GroupMember::Data(d) = m {
                Some(d)
            } else {
                None
            }
        })
        .collect()
}

fn group_groups(g: &Group) -> Vec<&Group> {
    g.members
        .iter()
        .filter_map(|m| {
            if let GroupMember::Group(gr) = m {
                Some(gr)
            } else {
                None
            }
        })
        .collect()
}

fn group_has_var_data(g: &Group) -> bool {
    if !group_data(g).is_empty() {
        return true;
    }
    for sub in group_groups(g) {
        if group_has_var_data(sub) {
            return true;
        }
    }
    false
}

/// Generate a collection of `(filename, contents)` tuples for the
/// supplied schema.
pub fn generate(schema: &Schema, opts: &GeneratorOptions) -> Vec<(String, String)> {
    let mut files = Vec::new();
    // always emit a types module
    let types_code = generate_types(&schema.types, opts);
    files.push(("types.rs".to_string(), types_code));
    // emit one file per message
    for msg in &schema.messages {
        let code = generate_message(msg, schema, opts);
        let fname = format!("{}.rs", msg.name.to_snake_case());
        files.push((fname, code));
    }
    // emit a mod.rs which links everything together
    let mod_code = generate_mod_rs(schema);
    files.push(("mod.rs".to_string(), mod_code));
    files
}

/// Generate the content of `mod.rs` re‑exporting messages and types.
fn generate_mod_rs(schema: &Schema) -> String {
    let mut mod_lines = String::new();
    mod_lines.push_str("// Automatically generated by sbe_gen.\n\n");
    mod_lines.push_str("pub mod types;\n");
    for msg in &schema.messages {
        let module = msg.name.to_snake_case();
        mod_lines.push_str(&format!("pub mod {};\n", module));
    }
    mod_lines.push('\n');
    mod_lines.push_str("// Re‑export message types\n");
    for msg in &schema.messages {
        let module = msg.name.to_snake_case();
        mod_lines.push_str(&format!("pub use {}::{};\n", module, msg.name));
    }
    mod_lines
}

/// Generate the `types.rs` module containing definitions of enums, sets and composites.
fn generate_types(
    types: &std::collections::HashMap<String, TypeDef>,
    opts: &GeneratorOptions,
) -> String {
    let mut code = String::new();
    code.push_str("// Automatically generated by sbe_gen.\n");
    code.push_str("use zerocopy::{FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned};\n");
    code.push_str(&format!(
        "use zerocopy::byteorder::{}_endian::*;\n",
        opts.endian
    ));
    code.push('\n');
    // for each type
    let mut sorted: Vec<_> = types.values().collect();
    // sort by name for deterministic output
    sorted.sort_by_key(|t| match t {
        TypeDef::Primitive { name, .. } => name.clone(),
        TypeDef::Enum { name, .. } => name.clone(),
        TypeDef::Set { name, .. } => name.clone(),
        TypeDef::Composite { name, .. } => name.clone(),
    });
    for ty in sorted {
        match ty {
            TypeDef::Primitive {
                name,
                primitive,
                length,
                presence,
                constant,
            } => {
                let rust_type = primitive_to_rust(primitive, opts);
                if rust_type.is_none() {
                    continue;
                }
                let rust_type = rust_type.unwrap();
                if let Some(len) = length {
                    code.push_str(&format!("pub type {} = [{}; {}];\n", name, rust_type, len));
                } else if presence.as_deref() == Some("constant") {
                    // define a constant rather than a type alias
                    if let Some(value) = constant {
                        code.push_str(&format!(
                            "pub const {}: {} = {} as {};\n",
                            name, rust_type, value, rust_type
                        ));
                    } else {
                        code.push_str(&format!(
                            "pub const {}: {} = {} as {};\n",
                            name,
                            rust_type,
                            primitive_default_value(primitive),
                            rust_type
                        ));
                    }
                } else {
                    code.push_str(&format!("pub type {} = {};\n", name, rust_type));
                }
            }
            TypeDef::Enum {
                name,
                encoding,
                values,
            } => {
                let rust_type = primitive_to_rust(encoding, opts).unwrap_or_else(|| "u8".into());
                code.push_str("#[repr(transparent)]\n");
                code.push_str(
                    "#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy, PartialEq, Eq)]\n",
                );
                code.push_str(&format!("pub struct {}(pub {});\n", name, rust_type));
                // define associated constants for variants
                if !values.is_empty() {
                    code.push_str(&format!("impl {} {{\n", name));
                    for (vname, val) in values {
                        // convert char values to numeric if necessary
                        let literal = if encoding == "char" {
                            if val.len() == 1 {
                                let c = val.chars().next().unwrap();
                                format!("{}u8", c as u32)
                            } else {
                                val.clone()
                            }
                        } else {
                            val.clone()
                        };
                        code.push_str(&format!(
                            "    pub const {}: Self = Self(<{}>::new({}));\n",
                            vname, rust_type, literal
                        ));
                    }
                    code.push_str("}\n");
                }
                code.push('\n');
            }
            TypeDef::Set {
                name,
                encoding,
                choices,
            } => {
                let rust_type = primitive_to_rust(encoding, opts).unwrap_or_else(|| "u8".into());
                code.push_str("#[repr(transparent)]\n");
                code.push_str(
                    "#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy, PartialEq, Eq)]\n",
                );
                code.push_str(&format!("pub struct {}(pub {});\n", name, rust_type));
                if !choices.is_empty() {
                    code.push_str(&format!("impl {} {{\n", name));
                    for (cname, bit) in choices {
                        // bit may be decimal or integer string
                        let bit_idx: u32 = bit.parse().unwrap_or(0);
                        code.push_str(&format!(
                            "    pub const {}: Self = Self(<{}>::new(1 << {}));\n",
                            cname, rust_type, bit_idx
                        ));
                    }
                    code.push_str("}\n");
                }
                code.push('\n');
            }
            TypeDef::Composite { name, fields } => {
                // generate a struct representing the composite
                code.push_str("#[repr(C)]\n");
                code.push_str(
                    "#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]\n",
                );
                code.push_str(&format!("pub struct {} {{\n", name));
                for f in fields {
                    match f {
                        CompositeField::Type {
                            name: fname,
                            primitive,
                            length,
                            presence: _,
                            constant: _,
                        } => {
                            if let Some(rust_type) = primitive_to_rust(primitive, opts) {
                                if let Some(len) = length {
                                    code.push_str(&format!(
                                        "    pub {}: [{}; {}],\n",
                                        fname.to_snake_case(),
                                        rust_type,
                                        len
                                    ));
                                } else {
                                    code.push_str(&format!(
                                        "    pub {}: {},\n",
                                        fname.to_snake_case(),
                                        rust_type
                                    ));
                                }
                            }
                        }
                        CompositeField::Ref { name: fname, ty } => {
                            code.push_str(&format!("    pub {}: {},\n", fname.to_snake_case(), ty));
                        }
                    }
                }
                code.push_str("}\n\n");
            }
        }
    }
    code
}

/// Generate the module for a single message.  This includes imports,
/// macro definition and the message struct itself.  Fields using
/// unsupported types are skipped.
fn generate_message(msg: &Message, schema: &Schema, opts: &GeneratorOptions) -> String {
    let fields = message_fields(msg);
    let groups = message_groups(msg);
    let data_fields = message_data(msg);
    let has_group_data = groups.iter().any(|g| group_has_var_data(g));
    let has_var_data = has_group_data || !data_fields.is_empty();
    let needs_mem = has_group_data || !groups.is_empty();
    let mut code = String::new();
    code.push_str("// Automatically generated by sbe_gen.\n");
    code.push_str(
        "use zerocopy::{Ref, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned};\n",
    );
    code.push_str(&format!(
        "use zerocopy::byteorder::{}_endian::*;\n",
        opts.endian
    ));
    code.push_str("use crate::types::*;\n\n");
    if needs_mem {
        code.push_str("use core::mem;\n");
    }
    if has_var_data {
        code.push_str("use core::str;\n");
    }
    if needs_mem || has_var_data {
        code.push('\n');
    }
    if has_var_data {
        code.push_str("#[derive(Debug, Clone, Copy)]\n");
        code.push_str(
            "pub struct VarData<'a> {\n    pub len: usize,\n    pub bytes: &'a [u8],\n}\n\n",
        );
        code.push_str("impl<'a> VarData<'a> {\n    pub fn as_str(&self) -> Option<&'a str> { str::from_utf8(self.bytes).ok() }\n}\n\n");
        code.push_str("#[derive(Clone, Copy)]\n");
        code.push_str("enum LengthKind { U8, U16, U32, U64 }\n\n");
        code.push_str("fn read_length(kind: LengthKind, buf: &[u8]) -> Option<(usize, &[u8])> {\n    match kind {\n        LengthKind::U8 => {\n            let (&b, rest) = buf.split_first()?;\n            Some((b as usize, rest))\n        }\n        LengthKind::U16 => {\n            let (v, rest) = Ref::<_, U16>::from_prefix(buf).ok()?;\n            Some((v.get() as usize, rest))\n        }\n        LengthKind::U32 => {\n            let (v, rest) = Ref::<_, U32>::from_prefix(buf).ok()?;\n            Some((v.get() as usize, rest))\n        }\n        LengthKind::U64 => {\n            let (v, rest) = Ref::<_, U64>::from_prefix(buf).ok()?;\n            Some((v.get() as usize, rest))\n        }\n    }\n}\n\n");
        code.push_str("fn parse_var_data<'a>(buf: &'a [u8], kind: LengthKind) -> Option<(VarData<'a>, &'a [u8])> {\n    let (len, rest) = read_length(kind, buf)?;\n    if rest.len() < len { return None; }\n    let (bytes, tail) = rest.split_at(len);\n    Some((VarData { len, bytes }, tail))\n}\n\n");
    }
    // macro definition
    code.push_str("#[macro_export]\nmacro_rules! zc_parse_prefix {\n    () => {\n        #[inline]\n        pub fn parse_prefix(body: &[u8]) -> Option<(&Self, &[u8])> {\n            Ref::<_, Self>::from_prefix(body)\n                .ok()\n                .map(|(r, b)| (Ref::into_ref(r), b))\n        }\n    };\n}\n\n");
    // struct definition
    code.push_str("#[repr(C)]\n");
    code.push_str(
        "#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]\n",
    );
    code.push_str(&format!("pub struct {} {{\n", msg.name));
    for field in &fields {
        // skip if presence constant: represented as const later
        if field.presence.as_deref() == Some("constant") {
            continue;
        }
        // skip if type not known or unsupported
        let ty_name = &field.ty;
        let field_name = field.name.to_snake_case();
        if let Some(rust_type) = resolve_type(ty_name, schema, opts) {
            code.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
        }
    }
    code.push_str("}\n\n");
    // associated constants for constant fields
    let const_fields: Vec<_> = fields
        .iter()
        .filter(|f| f.presence.as_deref() == Some("constant"))
        .collect();
    if !const_fields.is_empty() {
        code.push_str(&format!("impl {} {{\n", msg.name));
        for f in const_fields {
            let field_name = f.name.to_snake_case();
            // constant value may come from valueRef (enum variant) or direct numeric text on type def
            let ty = &f.ty;
            // if value_ref exists, try to reference type::Variant constant
            if let Some(vr) = &f.value_ref {
                // valueRef has form "TypeName.Variant"
                let parts: Vec<&str> = vr.split('.').collect();
                if parts.len() == 2 {
                    let type_name = parts[0];
                    let variant = parts[1];
                    code.push_str(&format!(
                        "    pub const {}: {} = {}::{};\n",
                        field_name.to_uppercase(),
                        type_name,
                        type_name,
                        variant
                    ));
                    continue;
                }
            }
            // otherwise, look up constant on type or parse as literal
            if let Some(TypeDef::Primitive {
                constant: Some(val),
                primitive,
                ..
            }) = schema.types.get(ty)
            {
                let rust_type = primitive_to_rust(primitive, opts).unwrap_or_else(|| "u8".into());
                code.push_str(&format!(
                    "    pub const {}: {} = {} as {};\n",
                    field_name.to_uppercase(),
                    rust_type,
                    val,
                    rust_type
                ));
            }
        }
        code.push_str("}\n\n");
    }
    // impl parse_prefix
    code.push_str(&format!("impl {} {{\n    zc_parse_prefix!();\n", msg.name));
    optional_methods_for_fields(&mut code, &fields, schema, opts, "self");
    if !data_fields.is_empty() {
        for d in &data_fields {
            let fn_name = d.name.to_snake_case();
            let kind = length_kind_token(length_kind_for_data(&d.ty, schema, opts));
            code.push_str(&format!(
                "    pub fn parse_{}<'a>(&self, buf: &'a [u8]) -> Option<(VarData<'a>, &'a [u8])> {{\n        parse_var_data(buf, {})\n    }}\n",
                fn_name, kind
            ));
        }
    }
    code.push_str("}\n\n");
    // group helpers (supports nesting)
    for g in groups {
        emit_group(g, schema, opts, &mut code);
    }
    code
}

/// Map an SBE primitive to a Rust zero‑copy type.  Returns `None` if
/// the primitive is not recognised.
fn primitive_to_rust(prim: &str, _opts: &GeneratorOptions) -> Option<String> {
    match prim {
        // boolean represented as u8
        "boolean" | "uint8" => Some("u8".into()),
        "int8" => Some("i8".into()),
        "char" => Some("u8".into()),
        "uint16" => Some("U16".into()),
        "int16" => Some("I16".into()),
        "uint32" => Some("U32".into()),
        "int32" => Some("I32".into()),
        "uint64" => Some("U64".into()),
        "int64" => Some("I64".into()),
        "float" => Some("F32".into()),
        "double" => Some("F64".into()),
        "varStringEncoding" | "varAsciiEncoding" | "varDataEncoding" => None,
        _ => None,
    }
}

/// Provide a default constant value for a primitive type.
fn primitive_default_value(prim: &str) -> &'static str {
    match prim {
        "int8" | "uint8" | "char" | "boolean" => "0",
        "int16" | "uint16" => "0",
        "int32" | "uint32" => "0",
        "int64" | "uint64" => "0",
        "float" => "0.0",
        "double" => "0.0",
        _ => "0",
    }
}

/// Resolve a field's type name to the appropriate Rust type.  This
/// consults the type map for user defined types or falls back to
/// primitive mapping.  Unsupported types return `None`, causing the
/// field to be skipped.
fn resolve_type(name: &str, schema: &Schema, opts: &GeneratorOptions) -> Option<String> {
    // first check if it's a primitive built‑in
    if let Some(rust) = primitive_to_rust(name, opts) {
        return Some(rust);
    }
    // check user defined types
    if let Some(td) = schema.types.get(name) {
        match td {
            TypeDef::Primitive {
                name: tname,
                length,
                ..
            } => {
                let rust = primitive_to_rust(&td_primitive(td), opts)?;
                if let Some(len) = length {
                    Some(format!("[{}; {}]", rust, len))
                } else {
                    Some(tname.clone())
                }
            }
            TypeDef::Enum { name: tname, .. } => Some(tname.clone()),
            TypeDef::Set { name: tname, .. } => Some(tname.clone()),
            TypeDef::Composite { name: tname, .. } => Some(tname.clone()),
        }
    } else {
        None
    }
}

fn td_primitive(td: &TypeDef) -> String {
    match td {
        TypeDef::Primitive { primitive, .. } => primitive.clone(),
        TypeDef::Enum { encoding, .. } => encoding.clone(),
        TypeDef::Set { encoding, .. } => encoding.clone(),
        TypeDef::Composite { .. } => "".into(),
    }
}

#[derive(Clone, Copy)]
enum LengthKind {
    U8,
    U16,
    U32,
    U64,
}

fn primitive_length_kind(prim: &str) -> Option<LengthKind> {
    match prim {
        "boolean" | "uint8" | "int8" | "char" => Some(LengthKind::U8),
        "uint16" | "int16" => Some(LengthKind::U16),
        "uint32" | "int32" => Some(LengthKind::U32),
        "uint64" | "int64" => Some(LengthKind::U64),
        _ => None,
    }
}

fn length_kind_for_data(ty: &str, schema: &Schema, opts: &GeneratorOptions) -> LengthKind {
    if let Some(kind) = primitive_length_kind(ty) {
        return kind;
    }
    if let Some(td) = schema.types.get(ty) {
        match td {
            TypeDef::Primitive { primitive, .. } => {
                if let Some(kind) = primitive_length_kind(primitive) {
                    return kind;
                }
            }
            TypeDef::Enum { encoding, .. } | TypeDef::Set { encoding, .. } => {
                if let Some(kind) = primitive_length_kind(encoding) {
                    return kind;
                }
            }
            TypeDef::Composite { fields, .. } => {
                for f in fields {
                    if let CompositeField::Type { primitive, .. } = f {
                        if let Some(kind) = primitive_length_kind(primitive) {
                            return kind;
                        }
                    }
                }
            }
        }
    }
    // fall back to little length prefix if unknown
    let _ = opts;
    LengthKind::U8
}

fn length_kind_token(kind: LengthKind) -> &'static str {
    match kind {
        LengthKind::U8 => "LengthKind::U8",
        LengthKind::U16 => "LengthKind::U16",
        LengthKind::U32 => "LengthKind::U32",
        LengthKind::U64 => "LengthKind::U64",
    }
}

fn emit_group(g: &Group, schema: &Schema, opts: &GeneratorOptions, code: &mut String) {
    let group_name = &g.name;
    let group_snake = g.name.to_snake_case();
    let entry_struct = format!("{}Entry", group_name);
    let entry_view = format!("{}EntryView", group_name);
    let group_struct = format!("{}Group", group_name);
    let iter_name = format!("{}Iter", group_name);
    let g_fields = group_fields(g);
    let g_data = group_data(g);
    let g_nested = group_groups(g);
    let has_data = !g_data.is_empty();
    let has_nested = !g_nested.is_empty();
    let has_any_var = has_data || has_nested;
    let dim = dimension_fields(schema, &g.dimension_type, opts);
    let block_len_expr = if let Some(bl) = g.block_length {
        bl.to_string()
    } else {
        format!("mem::size_of::<{}>()", entry_struct)
    };

    code.push_str(&format!(
        "pub fn parse_{}<'a>(buf: &'a [u8]) -> Option<{}<'a>> {{\n",
        group_snake, group_struct
    ));
    code.push_str(&format!(
        "    let (header, payload) = Ref::<_, {}>::from_prefix(buf).ok()?;\n",
        g.dimension_type
    ));
    code.push_str("    let header = Ref::into_ref(header);\n");
    code.push_str(&format!(
        "    let header_block_len = {};\n",
        to_usize_expr(&format!("header.{}", dim.block_field), &dim.block_field_ty)
    ));
    code.push_str(&format!(
        "    let declared = {} as usize;\n",
        block_len_expr
    ));
    code.push_str(
        "    let block_length = if header_block_len == 0 { declared } else { header_block_len };\n",
    );
    code.push_str(&format!(
        "    Some({} {{ header, payload, block_length }})\n",
        group_struct
    ));
    code.push_str("}\n\n");

    code.push_str(&format!(
        "pub struct {}<'a> {{\n    pub header: &'a {},\n    payload: &'a [u8],\n    block_length: usize,\n}}\n\n",
        group_struct, g.dimension_type
    ));
    code.push_str(&format!("impl<'a> {}<'a> {{\n", group_struct));
    code.push_str(&format!(
        "    pub fn count(&self) -> usize {{ {} }}\n",
        to_usize_expr(
            &format!("self.header.{}", dim.count_field),
            &dim.count_field_ty
        )
    ));
    code.push_str(&format!("    pub fn iter(&self) -> {}<'a> {{\n", iter_name));
    if has_data {
        code.push_str(&format!(
            "        static DATA_KINDS: [LengthKind; {}] = [{}];\n",
            g_data.len(),
            g_data
                .iter()
                .map(|d| length_kind_token(length_kind_for_data(&d.ty, schema, opts)))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        code.push_str(&format!(
            "        {} {{ remaining: self.payload, entries_left: self.count(), block_length: self.block_length, data_kinds: &DATA_KINDS }}\n",
            iter_name
        ));
    } else {
        code.push_str(&format!(
            "        {} {{ remaining: self.payload, entries_left: self.count(), block_length: self.block_length }}\n",
            iter_name
        ));
    }
    code.push_str("    }\n}\n\n");

    if has_data {
        code.push_str(&format!(
            "pub struct {}<'a> {{\n    remaining: &'a [u8],\n    entries_left: usize,\n    block_length: usize,\n    data_kinds: &'static [LengthKind],\n}}\n\n",
            iter_name
        ));
    } else {
        code.push_str(&format!(
            "pub struct {}<'a> {{\n    remaining: &'a [u8],\n    entries_left: usize,\n    block_length: usize,\n}}\n\n",
            iter_name
        ));
    }
    code.push_str(&format!(
        "impl<'a> {}<'a> {{\n    pub fn remainder(&self) -> &'a [u8] {{ self.remaining }}\n}}\n\n",
        iter_name
    ));

    code.push_str(&format!(
        "#[derive(Debug, Clone, Copy)]\npub struct {}<'a> {{\n    pub body: &'a {},\n",
        entry_view, entry_struct
    ));
    for nested in &g_nested {
        code.push_str(&format!(
            "    pub {}: {}Group<'a>,\n",
            nested.name.to_snake_case(),
            nested.name
        ));
    }
    for d in &g_data {
        code.push_str(&format!(
            "    pub {}: VarData<'a>,\n",
            d.name.to_snake_case()
        ));
    }
    code.push_str("}\n\n");

    code.push_str("#[repr(C)]\n");
    code.push_str(
        "#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]\n",
    );
    code.push_str(&format!("pub struct {} {{\n", entry_struct));
    for field in &g_fields {
        if field.presence.as_deref() == Some("constant") {
            continue;
        }
        let ty_name = &field.ty;
        let field_name = field.name.to_snake_case();
        if let Some(rust_type) = resolve_type(ty_name, schema, opts) {
            code.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
        }
    }
    code.push_str("}\n\n");
    if !g_fields.is_empty() {
        code.push_str(&format!("impl {} {{\n", entry_struct));
        optional_methods_for_fields(code, &g_fields, schema, opts, "self");
        code.push_str("}\n\n");
    }

    if has_any_var {
        code.push_str(&format!(
            "impl<'a> Iterator for {}<'a> {{\n    type Item = {}<'a>;\n    fn next(&mut self) -> Option<Self::Item> {{\n        if self.entries_left == 0 {{\n            return None;\n        }}\n        let (body, rest) = Ref::<_, {}>::from_prefix(self.remaining).ok()?;\n        let mut tail = rest;\n",
            iter_name, entry_view, entry_struct
        ));
        let mut data_idx = 0;
        for member in &g.members {
            match member {
                GroupMember::Group(nested) => {
                    code.push_str(&format!(
                        "        let nested_{name} = parse_{snake}(tail)?;\n",
                        name = nested.name.to_snake_case(),
                        snake = nested.name.to_snake_case()
                    ));
                    code.push_str(&format!(
                        "        let after_{name} = skip_{snake}(nested_{name}.payload, nested_{name}.count(), nested_{name}.block_length)?;\n        tail = after_{name};\n",
                        name = nested.name.to_snake_case(),
                        snake = nested.name.to_snake_case()
                    ));
                }
                GroupMember::Data(_) => {
                    code.push_str(&format!(
                        "        let (data_{idx}, after_{idx}) = parse_var_data(tail, *self.data_kinds.get({idx})?)?;\n        tail = after_{idx};\n",
                        idx = data_idx
                    ));
                    data_idx += 1;
                }
                GroupMember::Field(_) => {}
            }
        }
        code.push_str(
            "        self.remaining = tail;\n        self.entries_left -= 1;\n        Some(",
        );
        code.push_str(&format!("{} {{ body: Ref::into_ref(body)", entry_view));
        data_idx = 0;
        for member in &g.members {
            match member {
                GroupMember::Group(nested) => {
                    code.push_str(&format!(
                        ", {}: nested_{}",
                        nested.name.to_snake_case(),
                        nested.name.to_snake_case()
                    ));
                }
                GroupMember::Data(d) => {
                    code.push_str(&format!(", {}: data_{}", d.name.to_snake_case(), data_idx));
                    data_idx += 1;
                }
                GroupMember::Field(_) => {}
            }
        }
        code.push_str(" })\n    }\n}\n\n");
    } else {
        code.push_str(&format!("impl<'a> Iterator for {}<'a> {{\n", iter_name));
        code.push_str(&format!("    type Item = {}<'a>;\n", entry_view));
        code.push_str(
            "    fn next(&mut self) -> Option<Self::Item> {\n        if self.entries_left == 0 {\n            return None;\n        }\n",
        );
        code.push_str(&format!(
            "        let (body, tail) = Ref::<_, {}>::from_prefix(self.remaining).ok()?;\n",
            entry_struct
        ));
        code.push_str(
            "        self.remaining = tail;\n        self.entries_left -= 1;\n        Some(",
        );
        code.push_str(&format!("{} {{ body: Ref::into_ref(body) }}", entry_view));
        code.push_str(")\n    }\n}\n\n");
    }

    let has_var_members = g
        .members
        .iter()
        .any(|m| !matches!(m, GroupMember::Field(_)));
    code.push_str(&format!(
        "fn skip_{}<'a>(mut cursor: &'a [u8], count: usize, block_length: usize) -> Option<&'a [u8]> {{\n    for _ in 0..count {{\n",
        group_snake
    ));
    if !has_var_members {
        code.push_str("        if block_length == 0 { return None; }\n");
    }
    code.push_str(
        "        let mut tail = if block_length <= cursor.len() { &cursor[block_length..] } else { return None; };\n",
    );
    for member in g
        .members
        .iter()
        .filter(|m| !matches!(m, GroupMember::Field(_)))
    {
        match member {
            GroupMember::Group(nested) => {
                code.push_str(&format!(
                    "        let nested = parse_{}(tail)?;\n        tail = skip_{}(nested.payload, nested.count(), nested.block_length)?;\n",
                    nested.name.to_snake_case(),
                    nested.name.to_snake_case()
                ));
            }
            GroupMember::Data(d) => {
                let kind = length_kind_token(length_kind_for_data(&d.ty, schema, opts));
                code.push_str(&format!(
                    "        let (_, after_data) = parse_var_data(tail, {})?;\n        tail = after_data;\n",
                    kind
                ));
            }
            GroupMember::Field(_) => {}
        }
    }
    code.push_str("        cursor = tail;\n    }\n    Some(cursor)\n}\n\n");

    for nested in &g_nested {
        emit_group(nested, schema, opts, code);
    }
}

struct DimensionFields {
    block_field: String,
    block_field_ty: String,
    count_field: String,
    count_field_ty: String,
}

fn dimension_fields(schema: &Schema, dim_type: &str, opts: &GeneratorOptions) -> DimensionFields {
    if let Some(TypeDef::Composite { fields, .. }) = schema.types.get(dim_type) {
        let mut prim_fields = Vec::new();
        for f in fields {
            if let CompositeField::Type {
                name, primitive, ..
            } = f
            {
                if let Some(rust) = primitive_to_rust(primitive, opts) {
                    prim_fields.push((name.to_snake_case(), rust));
                }
            }
        }
        let block = prim_fields
            .iter()
            .find(|(n, _)| n.contains("block_length") || n.contains("blocklength"))
            .cloned()
            .or_else(|| prim_fields.first().cloned())
            .unwrap_or_else(|| ("block_length".into(), "U16".into()));
        let mut count = prim_fields
            .iter()
            .find(|(n, _)| n.contains("num_in_group") || n.contains("numingroup"))
            .cloned()
            .or_else(|| prim_fields.get(1).cloned())
            .unwrap_or_else(|| ("num_in_group".into(), "U16".into()));
        // allow block and count to be the same when only one field exists: duplicate
        if block.0 == count.0 && prim_fields.len() == 1 {
            count = ("num_in_group".into(), block.1.clone());
        }
        return DimensionFields {
            block_field: block.0,
            block_field_ty: block.1,
            count_field: count.0,
            count_field_ty: count.1,
        };
    }
    DimensionFields {
        block_field: "block_length".into(),
        block_field_ty: "U16".into(),
        count_field: "num_in_group".into(),
        count_field_ty: "U16".into(),
    }
}

fn to_usize_expr(field_name: &str, ty: &str) -> String {
    match ty {
        "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" => {
            format!("{} as usize", field_name)
        }
        _ => format!("{}.get() as usize", field_name),
    }
}

fn field_primitive(field: &Field, schema: &Schema) -> Option<String> {
    if let Some(td) = schema.types.get(&field.ty) {
        match td {
            TypeDef::Primitive { primitive, .. } => Some(primitive.clone()),
            TypeDef::Enum { encoding, .. } | TypeDef::Set { encoding, .. } => {
                Some(encoding.clone())
            }
            TypeDef::Composite { .. } => None,
        }
    } else {
        Some(field.ty.clone())
    }
}

fn optional_null_literal(prim: &str) -> Option<&'static str> {
    match prim {
        "boolean" | "uint8" | "char" => Some("u8::MAX"),
        "int8" => Some("i8::MIN"),
        "uint16" => Some("u16::MAX"),
        "int16" => Some("i16::MIN"),
        "uint32" => Some("u32::MAX"),
        "int32" => Some("i32::MIN"),
        "uint64" => Some("u64::MAX"),
        "int64" => Some("i64::MIN"),
        "float" => Some("f32::NAN"),
        "double" => Some("f64::NAN"),
        _ => None,
    }
}

fn optional_host_type(prim: &str) -> Option<&'static str> {
    match prim {
        "boolean" | "uint8" | "char" => Some("u8"),
        "int8" => Some("i8"),
        "uint16" => Some("u16"),
        "int16" => Some("i16"),
        "uint32" => Some("u32"),
        "int32" => Some("i32"),
        "uint64" => Some("u64"),
        "int64" => Some("i64"),
        "float" => Some("f32"),
        "double" => Some("f64"),
        _ => None,
    }
}

fn scalar_expr(expr: &str, rust_type: &str) -> Option<String> {
    match rust_type {
        "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" | "f32" | "f64" => {
            Some(expr.to_string())
        }
        "U16" | "I16" | "U32" | "I32" | "U64" | "I64" | "F32" | "F64" => {
            Some(format!("{}.get()", expr))
        }
        _ => None,
    }
}

fn optional_methods_for_fields(
    code: &mut String,
    fields: &[&Field],
    schema: &Schema,
    opts: &GeneratorOptions,
    self_expr: &str,
) {
    for field in fields {
        if field.presence.as_deref() != Some("optional") {
            continue;
        }
        let field_name = field.name.to_snake_case();
        let method_name = format!("{}_opt", field_name);

        let resolved_type = match resolve_type(&field.ty, schema, opts) {
            Some(t) => t,
            None => continue,
        };

        // Enum/set optional: return Option<EnumName> by inspecting the inner primitive
        if let Some(TypeDef::Enum { encoding, .. } | TypeDef::Set { encoding, .. }) =
            schema.types.get(&field.ty)
        {
            let inner_rust = match primitive_to_rust(encoding, opts) {
                Some(t) => t,
                None => continue,
            };
            if let Some(val_expr) =
                scalar_expr(&format!("{}.{}.0", self_expr, field_name), &inner_rust)
            {
                let host_type = match optional_host_type(encoding) {
                    Some(t) => t,
                    None => continue,
                };
                let null_val = match optional_null_literal(encoding) {
                    Some(v) => v,
                    None => continue,
                };
                let cond = if host_type == "f32" || host_type == "f64" {
                    "raw.is_nan()".to_string()
                } else {
                    format!("raw == {}", null_val)
                };
                code.push_str(&format!(
                    "    pub fn {method}(&self) -> Option<{ty}> {{\n        let v = {self_expr}.{field};\n        let raw = {val};\n        if {cond} {{ None }} else {{ Some(v) }}\n    }}\n",
                    method = method_name,
                    ty = field.ty,
                    self_expr = self_expr,
                    field = field_name,
                    val = val_expr,
                    cond = cond,
                ));
            }
            continue;
        }

        let prim = match field_primitive(field, schema) {
            Some(p) => p,
            None => continue,
        };
        let null_val = match optional_null_literal(&prim) {
            Some(v) => v,
            None => continue,
        };
        let host_type = match optional_host_type(&prim) {
            Some(t) => t,
            None => continue,
        };

        let scalar = scalar_expr(&format!("{}.{}", self_expr, field_name), &resolved_type);
        if let Some(val_expr) = scalar {
            let body = if host_type == "f32" || host_type == "f64" {
                format!(
                    "let v = {val}; if v.is_nan() {{ None }} else {{ Some(v) }}",
                    val = val_expr
                )
            } else {
                format!(
                    "let v = {val}; if v == {null} {{ None }} else {{ Some(v) }}",
                    val = val_expr,
                    null = null_val
                )
            };
            code.push_str(&format!(
                "    pub fn {method}(&self) -> Option<{ty}> {{ {body} }}\n",
                method = method_name,
                ty = host_type,
                body = body,
            ));
        }
    }
}
