//! Code generation for parsed SBE schemas.
//!
//! The generator produces one Rust module per message along with a
//! `types.rs` module which contains definitions for user defined
//! enums, sets and composites.  A `mod.rs` file is also emitted to
//! re‑export the generated types for ergonomic use.

use crate::parser::{Schema, TypeDef, CompositeField, Message, Field};
use crate::GeneratorOptions;
use heck::ToSnakeCase;

/// Generate a collection of `(filename, contents)` tuples for the
/// supplied schema.
pub fn generate(schema: &Schema, opts: &GeneratorOptions) -> Vec<(String, String)> {
    let mut files = Vec::new();
    // always emit a types module
    let types_code = generate_types(&schema.types, opts);
    files.push(("types.rs".to_string(), types_code));
    // emit one file per message
    for msg in &schema.messages {
        let code = generate_message(msg, schema, opts);
        let fname = format!("{}.rs", msg.name.to_snake_case());
        files.push((fname, code));
    }
    // emit a mod.rs which links everything together
    let mod_code = generate_mod_rs(schema);
    files.push(("mod.rs".to_string(), mod_code));
    files
}

/// Generate the content of `mod.rs` re‑exporting messages and types.
fn generate_mod_rs(schema: &Schema) -> String {
    let mut mod_lines = String::new();
    mod_lines.push_str("// Automatically generated by sbe_gen.\n\n");
    mod_lines.push_str("pub mod types;\n");
    for msg in &schema.messages {
        let module = msg.name.to_snake_case();
        mod_lines.push_str(&format!("pub mod {};&#x5c;n", module));
    }
    mod_lines.push_str("\n");
    mod_lines.push_str("// Re‑export message types\n");
    for msg in &schema.messages {
        let module = msg.name.to_snake_case();
        mod_lines.push_str(&format!("pub use {}::{};\n", module, msg.name));
    }
    mod_lines
}

/// Generate the `types.rs` module containing definitions of enums, sets and composites.
fn generate_types(types: &std::collections::HashMap<String, TypeDef>, opts: &GeneratorOptions) -> String {
    let mut code = String::new();
    code.push_str("// Automatically generated by sbe_gen.\n");
    code.push_str("use zerocopy::{FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned};\n");
    code.push_str(&format!("use zerocopy::byteorder::{}_endian::*;\n", opts.endian));
    code.push_str("\n");
    // for each type
    let mut sorted: Vec<_> = types.values().collect();
    // sort by name for deterministic output
    sorted.sort_by_key(|t| match t {
        TypeDef::Primitive { name, .. } => name.clone(),
        TypeDef::Enum { name, .. } => name.clone(),
        TypeDef::Set { name, .. } => name.clone(),
        TypeDef::Composite { name, .. } => name.clone(),
    });
    for ty in sorted {
        match ty {
            TypeDef::Primitive { name, primitive, length, presence, constant } => {
                let rust_type = primitive_to_rust(primitive, opts);
                if rust_type.is_none() { continue; }
                let rust_type = rust_type.unwrap();
                if let Some(len) = length {
                    code.push_str(&format!("pub type {} = [{}; {}];\n", name, rust_type, len));
                } else if presence.as_deref() == Some("constant") {
                    // define a constant rather than a type alias
                    if let Some(value) = constant {
                        code.push_str(&format!("pub const {}: {} = {} as {};\n", name, rust_type, value, rust_type));
                    } else {
                        code.push_str(&format!("pub const {}: {} = {} as {};\n", name, rust_type, primitive_default_value(primitive), rust_type));
                    }
                } else {
                    code.push_str(&format!("pub type {} = {};\n", name, rust_type));
                }
            }
            TypeDef::Enum { name, encoding, values } => {
                let rust_type = primitive_to_rust(encoding, opts).unwrap_or_else(|| "u8".into());
                code.push_str(&format!("#[repr(transparent)]\n"));
                code.push_str(&format!("#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy, PartialEq, Eq)]\n"));
                code.push_str(&format!("pub struct {}(pub {});\n", name, rust_type));
                // define associated constants for variants
                if !values.is_empty() {
                    code.push_str(&format!("impl {} {{\n", name));
                    for (vname, val) in values {
                        // convert char values to numeric if necessary
                        let literal = if encoding == "char" {
                            if val.len() == 1 {
                                let c = val.chars().next().unwrap();
                                format!("{}u8", c as u32)
                            } else {
                                format!("{}", val)
                            }
                        } else {
                            val.clone()
                        };
                        code.push_str(&format!("    pub const {}: Self = Self(<{}>::new({}));\n", vname, rust_type, literal));
                    }
                    code.push_str("}\n");
                }
                code.push_str("\n");
            }
            TypeDef::Set { name, encoding, choices } => {
                let rust_type = primitive_to_rust(encoding, opts).unwrap_or_else(|| "u8".into());
                code.push_str(&format!("#[repr(transparent)]\n"));
                code.push_str(&format!("#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy, PartialEq, Eq)]\n"));
                code.push_str(&format!("pub struct {}(pub {});\n", name, rust_type));
                if !choices.is_empty() {
                    code.push_str(&format!("impl {} {{\n", name));
                    for (cname, bit) in choices {
                        // bit may be decimal or integer string
                        let bit_idx: u32 = bit.parse().unwrap_or(0);
                        code.push_str(&format!("    pub const {}: Self = Self(<{}>::new(1 << {}));\n", cname, rust_type, bit_idx));
                    }
                    code.push_str("}\n");
                }
                code.push_str("\n");
            }
            TypeDef::Composite { name, fields } => {
                // generate a struct representing the composite
                code.push_str(&format!("#[repr(C)]\n"));
                code.push_str(&format!("#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]\n"));
                code.push_str(&format!("pub struct {} {{\n", name));
                for f in fields {
                    match f {
                        CompositeField::Type { name: fname, primitive, length, presence, constant } => {
                            if let Some(rust_type) = primitive_to_rust(primitive, opts) {
                                if let Some(len) = length {
                                    code.push_str(&format!("    pub {}: [{}; {}],\n", fname.to_snake_case(), rust_type, len));
                                } else {
                                    code.push_str(&format!("    pub {}: {},\n", fname.to_snake_case(), rust_type));
                                }
                            }
                        }
                        CompositeField::Ref { name: fname, ty } => {
                            code.push_str(&format!("    pub {}: {},\n", fname.to_snake_case(), ty));
                        }
                    }
                }
                code.push_str("}\n\n");
            }
        }
    }
    code
}

/// Generate the module for a single message.  This includes imports,
/// macro definition and the message struct itself.  Fields using
/// unsupported types are skipped.
fn generate_message(msg: &Message, schema: &Schema, opts: &GeneratorOptions) -> String {
    let mut code = String::new();
    code.push_str("// Automatically generated by sbe_gen.\n");
    code.push_str("use zerocopy::{Ref, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned};\n");
    code.push_str(&format!("use zerocopy::byteorder::{}_endian::*;\n", opts.endian));
    code.push_str("use crate::types::*;\n\n");
    // macro definition
    code.push_str("#[macro_export]\nmacro_rules! zc_parse_prefix {\n    () => {\n        #[inline]\n        pub fn parse_prefix(body: &[u8]) -> Option<(&Self, &[u8])> {\n            Ref::<_, Self>::from_prefix(body)\n                .ok()\n                .map(|(r, b)| (Ref::into_ref(r), b))\n        }\n    };\n}\n\n");
    // struct definition
    code.push_str("#[repr(C)]\n");
    code.push_str("#[derive(Debug, FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Clone, Copy)]\n");
    code.push_str(&format!("pub struct {} {{\n", msg.name));
    for field in &msg.fields {
        // skip if presence constant: represented as const later
        if field.presence.as_deref() == Some("constant") {
            continue;
        }
        // skip if type not known or unsupported
        let ty_name = &field.ty;
        let field_name = field.name.to_snake_case();
        if let Some(rust_type) = resolve_type(ty_name, schema, opts) {
            code.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
        }
    }
    code.push_str("}\n\n");
    // associated constants for constant fields
    let const_fields: Vec<_> = msg.fields.iter().filter(|f| f.presence.as_deref() == Some("constant")).collect();
    if !const_fields.is_empty() {
        code.push_str(&format!("impl {} {{\n", msg.name));
        for f in const_fields {
            let field_name = f.name.to_snake_case();
            // constant value may come from valueRef (enum variant) or direct numeric text on type def
            let ty = &f.ty;
            // if value_ref exists, try to reference type::Variant constant
            if let Some(vr) = &f.value_ref {
                // valueRef has form "TypeName.Variant"
                let parts: Vec<&str> = vr.split('.').collect();
                if parts.len() == 2 {
                    let type_name = parts[0];
                    let variant = parts[1];
                    code.push_str(&format!("    pub const {}: {} = {}::{};\n", field_name.to_uppercase(), type_name, type_name, variant));
                    continue;
                }
            }
            // otherwise, look up constant on type or parse as literal
            if let Some(td) = schema.types.get(ty) {
                match td {
                    TypeDef::Primitive { constant: Some(val), primitive, .. } => {
                        let rust_type = primitive_to_rust(primitive, opts).unwrap_or_else(|| "u8".into());
                        code.push_str(&format!("    pub const {}: {} = {} as {};\n", field_name.to_uppercase(), rust_type, val, rust_type));
                    }
                    _ => {}
                }
            }
        }
        code.push_str("}\n\n");
    }
    // impl parse_prefix
    code.push_str(&format!("impl {} {{\n    zc_parse_prefix!();\n}}\n", msg.name));
    code
}

/// Map an SBE primitive to a Rust zero‑copy type.  Returns `None` if
/// the primitive is not recognised.
fn primitive_to_rust(prim: &str, opts: &GeneratorOptions) -> Option<String> {
    let endian_mod = format!("{}_endian", opts.endian);
    match prim {
        // boolean represented as u8
        "boolean" | "uint8" => Some("u8".into()),
        "int8" => Some("i8".into()),
        "char" => Some("u8".into()),
        "uint16" => Some("U16".into()),
        "int16" => Some("I16".into()),
        "uint32" => Some("U32".into()),
        "int32" => Some("I32".into()),
        "uint64" => Some("U64".into()),
        "int64" => Some("I64".into()),
        "float" => Some("F32".into()),
        "double" => Some("F64".into()),
        "varStringEncoding" | "varAsciiEncoding" | "varDataEncoding" => None,
        _ => None,
    }
}

/// Provide a default constant value for a primitive type.
fn primitive_default_value(prim: &str) -> &'static str {
    match prim {
        "int8" | "uint8" | "char" | "boolean" => "0",
        "int16" | "uint16" => "0",
        "int32" | "uint32" => "0",
        "int64" | "uint64" => "0",
        "float" => "0.0",
        "double" => "0.0",
        _ => "0",
    }
}

/// Resolve a field's type name to the appropriate Rust type.  This
/// consults the type map for user defined types or falls back to
/// primitive mapping.  Unsupported types return `None`, causing the
/// field to be skipped.
fn resolve_type(name: &str, schema: &Schema, opts: &GeneratorOptions) -> Option<String> {
    // first check if it's a primitive built‑in
    if let Some(rust) = primitive_to_rust(name, opts) {
        return Some(rust);
    }
    // check user defined types
    if let Some(td) = schema.types.get(name) {
        match td {
            TypeDef::Primitive { name: tname, length, .. } => {
                let rust = primitive_to_rust(&td_primitive(td), opts)?;
                if let Some(len) = length {
                    Some(format!("[{}; {}]", rust, len))
                } else {
                    Some(tname.clone())
                }
            }
            TypeDef::Enum { name: tname, .. } => Some(tname.clone()),
            TypeDef::Set { name: tname, .. } => Some(tname.clone()),
            TypeDef::Composite { name: tname, .. } => Some(tname.clone()),
        }
    } else {
        None
    }
}

fn td_primitive(td: &TypeDef) -> String {
    match td {
        TypeDef::Primitive { primitive, .. } => primitive.clone(),
        TypeDef::Enum { encoding, .. } => encoding.clone(),
        TypeDef::Set { encoding, .. } => encoding.clone(),
        TypeDef::Composite { .. } => "".into(),
    }
}